In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df.drop(['PassengerId', 'Name','SibSp','Parch', 'Ticket','Cabin', 'Embarked'], axis = 'columns', inplace = True)
df


Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [7]:
inputs = df.drop("Survived", axis = "columns")
target = df.Survived

In [8]:
#input.Sex = input.Sex.map({"male" :1, "female" : 2})

In [9]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [10]:
inputs = pd.concat([inputs, dummies], axis = "columns")

In [11]:
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

### I am dropping male column as well because of dummy variable trap theory. One column is enough to represent male vs female

In [12]:
inputs.drop(["Sex", "male"], axis = "columns", inplace = True)
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [13]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [14]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [15]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [17]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.3)

In [18]:
model = GaussianNB()

In [19]:
model.fit(X_train, y_train)

GaussianNB()

In [20]:
model.score(X_test, y_test)

0.7910447761194029

In [21]:
X_test[0:10]

Pclass        Age      Fare  female
647       1  56.000000   35.5000       0
232       2  59.000000   13.5000       0
762       3  20.000000    7.2292       0
739       3  29.699118    7.8958       0
489       3   9.000000   15.9000       0
135       2  23.000000   15.0458       0
347       3  29.699118   16.1000       1
874       2  28.000000   24.0000       1
377       1  27.000000  211.5000       0
528       3  39.000000    7.9250       0

In [22]:
y_test[:10]

647    1
232    0
762    1
739    0
489    1
135    0
347    1
874    1
377    0
528    0
Name: Survived, dtype: int64

In [23]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [24]:
model.predict_proba(X_test[:10])

array([[7.07779746e-01, 2.92220254e-01],
       [8.96251378e-01, 1.03748622e-01],
       [9.61448412e-01, 3.85515878e-02],
       [9.66110700e-01, 3.38893002e-02],
       [9.49498586e-01, 5.05014137e-02],
       [9.24793122e-01, 7.52068782e-02],
       [4.54811688e-01, 5.45188312e-01],
       [2.67500262e-01, 7.32499738e-01],
       [2.91570454e-06, 9.99997084e-01],
       [9.66044809e-01, 3.39551909e-02]])

### Calculate the score using cross validation

In [25]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(), X_train, y_train, cv= 10)

array([0.74603175, 0.74603175, 0.85714286, 0.77419355, 0.79032258,
       0.72580645, 0.67741935, 0.70967742, 0.79032258, 0.80645161])